# GitHub Pages configuration
baseurl: "/persian-datepicker-element"
url: "https://mehrabix.github.io"

# Disable Jekyll processing for these folders
exclude:
  - node_modules
  - dist
  - .github

# Enable relative permalinks
permalink: pretty

# Set encoding to UTF-8
encoding: utf-8 